<?xml version="1.0" encoding="UTF-8"?>
<robot generator="Robot 7.2 (Python 3.12.8 on win32)" generated="2025-01-26T22:15:27.819779" rpa="false" schemaversion="5">
<suite id="s1" name="Test User Massa" source="c:\iterasys\PetStoreRobot11\__tests__\api\test_user_massa.robot">
<test id="s1-t1" name="Post User" line="11">
<msg time="2025-01-26T22:15:28.451463" level="INFO">${DataDriver_TEST_DATA} = {'ERROR': 'Test Case not found...'}</msg>
<kw name="Create User DDT">
<msg time="2025-01-26T22:15:28.453517" level="FAIL">Variable '${id}' not found.</msg>
<arg>${id}</arg>
<arg>${username}</arg>
<arg>${firstName}</arg>
<arg>${lastName}</arg>
<arg>${email}</arg>
<arg>${password}</arg>
<arg>${phone}</arg>
<arg>${userStatus}</arg>
<status status="FAIL" start="2025-01-26T22:15:28.452518" elapsed="0.000999">Variable '${id}' not found.</status>
</kw>
<status status="FAIL" start="2025-01-26T22:15:28.450416" elapsed="0.003101">Variable '${id}' not found.</status>
</test>
<status status="FAIL" start="2025-01-26T22:15:27.827790" elapsed="0.629201"/>
</suite>
<statistics>
<total>
<stat pass="0" fail="1" skip="0">All Tests</stat>
</total>
<tag>
</tag>
<suite>
<stat name="Test User Massa" id="s1" pass="0" fail="1" skip="0">Test User Massa</stat>
</suite>
</statistics>
<errors>
<msg time="2025-01-26T22:15:28.440544" level="ERROR">[ DataDriver ] Error in robot file:
  File "c:\iterasys\PetStoreRobot11\__tests__\api\test_user_massa.robot", line 0</msg>
<msg time="2025-01-26T22:15:28.443953" level="ERROR">In source file:
  File "c:\iterasys\PetStoreRobot11\__tests__\api\..\..\fixtures\csv\user1.csv", line 3</msg>
<msg time="2025-01-26T22:15:28.449109" level="ERROR">Calling method '_start_suite' of listener 'DataDriver' failed: IndexError: list index out of range</msg>
</errors>
</robot>
